#[allow(dead_code)]
pub enum Instruction {
    ADDHL(GroupedArithmeticTarget),

    ADD(ArithmeticTarget),
    ADC(ArithmeticTarget),
    SUB(ArithmeticTarget),
    SBC(ArithmeticTarget),
    AND(ArithmeticTarget),
    OR(ArithmeticTarget),
    XOR(ArithmeticTarget),
    CP(ArithmeticTarget),
    SRL(ArithmeticTarget),
    RR(ArithmeticTarget),
    RL(ArithmeticTarget),
    RRC(ArithmeticTarget),
    RLC(ArithmeticTarget),
    SRA(ArithmeticTarget),
    SLA(ArithmeticTarget),
    SWAP(ArithmeticTarget),

    INC(IncDecTarget),
    DEC(IncDecTarget),

    CCF,
    SCF,
    RRA,
    RLA,
    RRCA,
    RLCA,
    CPL,
    JPI,

    BIT(ArithmeticTarget, BitPosition),
    RESET(ArithmeticTarget, BitPosition),
    SET(ArithmeticTarget, BitPosition),

    JP(JumpCondition),
    JR(JumpCondition),

    LD(LoadType),
}

pub enum ArithmeticTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
}

#[allow(dead_code)]
pub enum GroupedArithmeticTarget {
    BC,
    DE,
    HL,
}

#[allow(dead_code)]
pub enum IncDecTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    BC,
    DE,
    HL,
}

pub enum BitPosition {
    B0,
    B1,
    B2,
    B3,
    B4,
    B5,
    B6,
    B7,
}

pub enum JumpCondition {
    NotZero,
    Zero,
    NotCarry,
    Carry,
    Always,
}

pub enum LoadType {
    Byte(LoadByteTarget, LoadByteSrc),
    Word(LoadWordTarget),
    AFromIndirect(IndirectSrc),
    IndirectFromA(IndirectSrc),
    AFromByteAddress,
    ByteAddressFromA,
}

pub enum LoadByteTarget {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    HLI,
}

pub enum LoadByteSrc {
    A,
    B,
    C,
    D,
    E,
    H,
    L,
    D8,
    HLI,
}

pub enum LoadWordTarget {
    BC,
    DE,
    HL,
}

pub enum IndirectSrc {
    BC,
    DE,
    HLMinus,
    HLPlus,
    D8,
    IOPortC,
}

impl std::convert::From<BitPosition> for u8 {
    fn from(bit: BitPosition) -> u8 {
	match bit {
	    BitPosition::B0 => 0,
	    BitPosition::B1 => 1,
	    BitPosition::B2 => 2,
	    BitPosition::B3 => 3,
	    BitPosition::B4 => 4,
	    BitPosition::B5 => 5,
	    BitPosition::B6 => 6,
	    BitPosition::B7 => 7,
	}
    }
}

impl Instruction {
    pub fn from_byte(instruction_address: u8, is_prefixed: bool) -> Option<Instruction> {
	if is_prefixed {
	    Instruction::from_byte_prefixed(instruction_address)
	} else {
	    Instruction::from_byte_not_prefixed(instruction_address)
	}
    }

    fn from_byte_prefixed(instruction_address: u8) -> Option<Instruction> {
	match instruction_address {
            0x00 => Some(Instruction::RLC(ArithmeticTarget::B)),
            0x01 => Some(Instruction::RLC(ArithmeticTarget::C)),
            0x02 => Some(Instruction::RLC(ArithmeticTarget::D)),
            0x03 => Some(Instruction::RLC(ArithmeticTarget::E)),
            0x04 => Some(Instruction::RLC(ArithmeticTarget::H)),
            0x05 => Some(Instruction::RLC(ArithmeticTarget::L)),
            0x07 => Some(Instruction::RLC(ArithmeticTarget::A)),

            0x08 => Some(Instruction::RRC(ArithmeticTarget::B)),
            0x09 => Some(Instruction::RRC(ArithmeticTarget::C)),
            0x0a => Some(Instruction::RRC(ArithmeticTarget::D)),
            0x0b => Some(Instruction::RRC(ArithmeticTarget::E)),
            0x0c => Some(Instruction::RRC(ArithmeticTarget::H)),
            0x0d => Some(Instruction::RRC(ArithmeticTarget::L)),
            0x0f => Some(Instruction::RRC(ArithmeticTarget::A)),

            0x10 => Some(Instruction::RL(ArithmeticTarget::B)),
            0x11 => Some(Instruction::RL(ArithmeticTarget::C)),
            0x12 => Some(Instruction::RL(ArithmeticTarget::D)),
            0x13 => Some(Instruction::RL(ArithmeticTarget::E)),
            0x14 => Some(Instruction::RL(ArithmeticTarget::H)),
            0x15 => Some(Instruction::RL(ArithmeticTarget::L)),
            0x17 => Some(Instruction::RL(ArithmeticTarget::A)),

            0x18 => Some(Instruction::RR(ArithmeticTarget::B)),
            0x19 => Some(Instruction::RR(ArithmeticTarget::C)),
            0x1a => Some(Instruction::RR(ArithmeticTarget::D)),
            0x1b => Some(Instruction::RR(ArithmeticTarget::E)),
            0x1c => Some(Instruction::RR(ArithmeticTarget::H)),
            0x1d => Some(Instruction::RR(ArithmeticTarget::L)),
            0x1f => Some(Instruction::RR(ArithmeticTarget::A)),

            0x20 => Some(Instruction::SLA(ArithmeticTarget::B)),
            0x21 => Some(Instruction::SLA(ArithmeticTarget::C)),
            0x22 => Some(Instruction::SLA(ArithmeticTarget::D)),
            0x23 => Some(Instruction::SLA(ArithmeticTarget::E)),
            0x24 => Some(Instruction::SLA(ArithmeticTarget::H)),
            0x25 => Some(Instruction::SLA(ArithmeticTarget::L)),
            0x27 => Some(Instruction::SLA(ArithmeticTarget::A)),

            0x28 => Some(Instruction::SRA(ArithmeticTarget::B)),
            0x29 => Some(Instruction::SRA(ArithmeticTarget::C)),
            0x2a => Some(Instruction::SRA(ArithmeticTarget::D)),
            0x2b => Some(Instruction::SRA(ArithmeticTarget::E)),
            0x2c => Some(Instruction::SRA(ArithmeticTarget::H)),
            0x2d => Some(Instruction::SRA(ArithmeticTarget::L)),
            0x2f => Some(Instruction::SRA(ArithmeticTarget::A)),

            0x30 => Some(Instruction::SWAP(ArithmeticTarget::B)),
            0x31 => Some(Instruction::SWAP(ArithmeticTarget::C)),
            0x32 => Some(Instruction::SWAP(ArithmeticTarget::D)),
            0x33 => Some(Instruction::SWAP(ArithmeticTarget::E)),
            0x34 => Some(Instruction::SWAP(ArithmeticTarget::H)),
            0x35 => Some(Instruction::SWAP(ArithmeticTarget::L)),
            0x37 => Some(Instruction::SWAP(ArithmeticTarget::A)),

            0x38 => Some(Instruction::SRL(ArithmeticTarget::B)),
            0x39 => Some(Instruction::SRL(ArithmeticTarget::C)),
            0x3a => Some(Instruction::SRL(ArithmeticTarget::D)),
            0x3b => Some(Instruction::SRL(ArithmeticTarget::E)),
            0x3c => Some(Instruction::SRL(ArithmeticTarget::H)),
            0x3d => Some(Instruction::SRL(ArithmeticTarget::L)),
            0x3f => Some(Instruction::SRL(ArithmeticTarget::A)),

            0x40 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B0)),
            0x41 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B0)),
            0x42 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B0)),
            0x43 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B0)),
            0x44 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B0)),
            0x45 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B0)),
            0x47 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B0)),

            0x48 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B1)),
            0x49 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B1)),
            0x4a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B1)),
            0x4b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B1)),
            0x4c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B1)),
            0x4d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B1)),
            0x4f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B1)),

            0x50 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B2)),
            0x51 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B2)),
            0x52 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B2)),
            0x53 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B2)),
            0x54 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B2)),
            0x55 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B2)),
            0x57 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B2)),

            0x58 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B3)),
            0x59 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B3)),
            0x5a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B3)),
            0x5b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B3)),
            0x5c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B3)),
            0x5d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B3)),
            0x5f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B3)),

            0x60 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B4)),
            0x61 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B4)),
            0x62 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B4)),
            0x63 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B4)),
            0x64 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B4)),
            0x65 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B4)),
            0x67 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B4)),

            0x68 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B5)),
            0x69 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B5)),
            0x6a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B5)),
            0x6b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B5)),
            0x6c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B5)),
            0x6d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B5)),
            0x6f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B5)),

            0x70 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B6)),
            0x71 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B6)),
            0x72 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B6)),
            0x73 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B6)),
            0x74 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B6)),
            0x75 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B6)),
            0x77 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B6)),

            0x78 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B7)),
            0x79 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B7)),
            0x7a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B7)),
            0x7b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B7)),
            0x7c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B7)),
            0x7d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B7)),
            0x7f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B7)),

            0x80 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B0)),
            0x81 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B0)),
            0x82 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B0)),
            0x83 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B0)),
            0x84 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B0)),
            0x85 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B0)),
            0x87 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B0)),

            0x88 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B1)),
            0x89 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B1)),
            0x8a => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B1)),
            0x8b => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B1)),
            0x8c => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B1)),
            0x8d => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B1)),
            0x8f => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B1)),

            0x90 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B2)),
            0x91 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B2)),
            0x92 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B2)),
            0x93 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B2)),
            0x94 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B2)),
            0x95 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B2)),
            0x97 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B2)),

            0x98 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B3)),
            0x99 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B3)),
            0x9a => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B3)),
            0x9b => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B3)),
            0x9c => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B3)),
            0x9d => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B3)),
            0x9f => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B3)),

            0xa0 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B4)),
            0xa1 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B4)),
            0xa2 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B4)),
            0xa3 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B4)),
            0xa4 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B4)),
            0xa5 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B4)),
            0xa7 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B4)),

            0xa8 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B5)),
            0xa9 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B5)),
            0xaa => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B5)),
            0xab => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B5)),
            0xac => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B5)),
            0xad => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B5)),
            0xaf => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B5)),

            0xb0 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B6)),
            0xb1 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B6)),
            0xb2 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B6)),
            0xb3 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B6)),
            0xb4 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B6)),
            0xb5 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B6)),
            0xb7 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B6)),

            0xb8 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B7)),
            0xb9 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B7)),
            0xba => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B7)),
            0xbb => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B7)),
            0xbc => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B7)),
            0xbd => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B7)),
            0xbf => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B7)),

            0xc0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B0)),
            0xc1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B0)),
            0xc2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B0)),
            0xc3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B0)),
            0xc4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B0)),
            0xc5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B0)),
            0xc7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B0)),

            0xc8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B1)),
            0xc9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B1)),
            0xca => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B1)),
            0xcb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B1)),
            0xcc => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B1)),
            0xcd => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B1)),
            0xcf => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B1)),

            0xd0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B2)),
            0xd1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B2)),
            0xd2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B2)),
            0xd3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B2)),
            0xd4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B2)),
            0xd5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B2)),
            0xd7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B2)),

            0xd8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B3)),
            0xd9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B3)),
            0xda => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B3)),
            0xdb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B3)),
            0xdc => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B3)),
            0xdd => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B3)),
            0xdf => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B3)),

            0xe0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B4)),
            0xe1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B4)),
            0xe2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B4)),
            0xe3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B4)),
            0xe4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B4)),
            0xe5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B4)),
            0xe7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B4)),

            0xe8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B5)),
            0xe9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B5)),
            0xea => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B5)),
            0xeb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B5)),
            0xec => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B5)),
            0xed => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B5)),
            0xef => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B5)),

            0xf0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B6)),
            0xf1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B6)),
            0xf2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B6)),
            0xf3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B6)),
            0xf4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B6)),
            0xf5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B6)),
            0xf7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B6)),

            0xf8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B7)),
            0xf9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B7)),
            0xfa => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B7)),
            0xfb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B7)),
            0xfc => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B7)),
            0xfd => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B7)),
            0xff => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B7)),

	    _ => None,
        }
    }

    fn from_byte_not_prefixed(instruction_address: u8) -> Option<Instruction> {
	match instruction_address {
            0x00 => Some(Instruction::RLC(ArithmeticTarget::B)),
            0x01 => Some(Instruction::RLC(ArithmeticTarget::C)),
            0x02 => Some(Instruction::RLC(ArithmeticTarget::D)),
            0x03 => Some(Instruction::RLC(ArithmeticTarget::E)),
            0x04 => Some(Instruction::RLC(ArithmeticTarget::H)),
            0x05 => Some(Instruction::RLC(ArithmeticTarget::L)),
            0x07 => Some(Instruction::RLC(ArithmeticTarget::A)),

            0x08 => Some(Instruction::RRC(ArithmeticTarget::B)),
            0x09 => Some(Instruction::RRC(ArithmeticTarget::C)),
            0x0a => Some(Instruction::RRC(ArithmeticTarget::D)),
            0x0b => Some(Instruction::RRC(ArithmeticTarget::E)),
            0x0c => Some(Instruction::RRC(ArithmeticTarget::H)),
            0x0d => Some(Instruction::RRC(ArithmeticTarget::L)),
            0x0f => Some(Instruction::RRC(ArithmeticTarget::A)),

            0x10 => Some(Instruction::RL(ArithmeticTarget::B)),
            0x11 => Some(Instruction::RL(ArithmeticTarget::C)),
            0x12 => Some(Instruction::RL(ArithmeticTarget::D)),
            0x13 => Some(Instruction::RL(ArithmeticTarget::E)),
            0x14 => Some(Instruction::RL(ArithmeticTarget::H)),
            0x15 => Some(Instruction::RL(ArithmeticTarget::L)),
            0x17 => Some(Instruction::RL(ArithmeticTarget::A)),

            0x18 => Some(Instruction::RR(ArithmeticTarget::B)),
            0x19 => Some(Instruction::RR(ArithmeticTarget::C)),
            0x1a => Some(Instruction::RR(ArithmeticTarget::D)),
            0x1b => Some(Instruction::RR(ArithmeticTarget::E)),
            0x1c => Some(Instruction::RR(ArithmeticTarget::H)),
            0x1d => Some(Instruction::RR(ArithmeticTarget::L)),
            0x1f => Some(Instruction::RR(ArithmeticTarget::A)),

            0x20 => Some(Instruction::SLA(ArithmeticTarget::B)),
            0x21 => Some(Instruction::SLA(ArithmeticTarget::C)),
            0x22 => Some(Instruction::SLA(ArithmeticTarget::D)),
            0x23 => Some(Instruction::SLA(ArithmeticTarget::E)),
            0x24 => Some(Instruction::SLA(ArithmeticTarget::H)),
            0x25 => Some(Instruction::SLA(ArithmeticTarget::L)),
            0x27 => Some(Instruction::SLA(ArithmeticTarget::A)),

            0x28 => Some(Instruction::SRA(ArithmeticTarget::B)),
            0x29 => Some(Instruction::SRA(ArithmeticTarget::C)),
            0x2a => Some(Instruction::SRA(ArithmeticTarget::D)),
            0x2b => Some(Instruction::SRA(ArithmeticTarget::E)),
            0x2c => Some(Instruction::SRA(ArithmeticTarget::H)),
            0x2d => Some(Instruction::SRA(ArithmeticTarget::L)),
            0x2f => Some(Instruction::SRA(ArithmeticTarget::A)),

            0x30 => Some(Instruction::SWAP(ArithmeticTarget::B)),
            0x31 => Some(Instruction::SWAP(ArithmeticTarget::C)),
            0x32 => Some(Instruction::SWAP(ArithmeticTarget::D)),
            0x33 => Some(Instruction::SWAP(ArithmeticTarget::E)),
            0x34 => Some(Instruction::SWAP(ArithmeticTarget::H)),
            0x35 => Some(Instruction::SWAP(ArithmeticTarget::L)),
            0x37 => Some(Instruction::SWAP(ArithmeticTarget::A)),

            0x38 => Some(Instruction::SRL(ArithmeticTarget::B)),
            0x39 => Some(Instruction::SRL(ArithmeticTarget::C)),
            0x3a => Some(Instruction::SRL(ArithmeticTarget::D)),
            0x3b => Some(Instruction::SRL(ArithmeticTarget::E)),
            0x3c => Some(Instruction::SRL(ArithmeticTarget::H)),
            0x3d => Some(Instruction::SRL(ArithmeticTarget::L)),
            0x3f => Some(Instruction::SRL(ArithmeticTarget::A)),

            0x40 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B0)),
            0x41 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B0)),
            0x42 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B0)),
            0x43 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B0)),
            0x44 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B0)),
            0x45 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B0)),
            0x47 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B0)),

            0x48 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B1)),
            0x49 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B1)),
            0x4a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B1)),
            0x4b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B1)),
            0x4c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B1)),
            0x4d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B1)),
            0x4f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B1)),

            0x50 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B2)),
            0x51 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B2)),
            0x52 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B2)),
            0x53 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B2)),
            0x54 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B2)),
            0x55 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B2)),
            0x57 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B2)),

            0x58 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B3)),
            0x59 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B3)),
            0x5a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B3)),
            0x5b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B3)),
            0x5c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B3)),
            0x5d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B3)),
            0x5f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B3)),

            0x60 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B4)),
            0x61 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B4)),
            0x62 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B4)),
            0x63 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B4)),
            0x64 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B4)),
            0x65 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B4)),
            0x67 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B4)),

            0x68 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B5)),
            0x69 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B5)),
            0x6a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B5)),
            0x6b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B5)),
            0x6c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B5)),
            0x6d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B5)),
            0x6f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B5)),

            0x70 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B6)),
            0x71 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B6)),
            0x72 => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B6)),
            0x73 => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B6)),
            0x74 => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B6)),
            0x75 => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B6)),
            0x77 => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B6)),

            0x78 => Some(Instruction::BIT(ArithmeticTarget::B, BitPosition::B7)),
            0x79 => Some(Instruction::BIT(ArithmeticTarget::C, BitPosition::B7)),
            0x7a => Some(Instruction::BIT(ArithmeticTarget::D, BitPosition::B7)),
            0x7b => Some(Instruction::BIT(ArithmeticTarget::E, BitPosition::B7)),
            0x7c => Some(Instruction::BIT(ArithmeticTarget::H, BitPosition::B7)),
            0x7d => Some(Instruction::BIT(ArithmeticTarget::L, BitPosition::B7)),
            0x7f => Some(Instruction::BIT(ArithmeticTarget::A, BitPosition::B7)),

            0x80 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B0)),
            0x81 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B0)),
            0x82 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B0)),
            0x83 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B0)),
            0x84 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B0)),
            0x85 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B0)),
            0x87 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B0)),

            0x88 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B1)),
            0x89 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B1)),
            0x8a => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B1)),
            0x8b => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B1)),
            0x8c => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B1)),
            0x8d => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B1)),
            0x8f => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B1)),

            0x90 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B2)),
            0x91 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B2)),
            0x92 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B2)),
            0x93 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B2)),
            0x94 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B2)),
            0x95 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B2)),
            0x97 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B2)),

            0x98 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B3)),
            0x99 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B3)),
            0x9a => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B3)),
            0x9b => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B3)),
            0x9c => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B3)),
            0x9d => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B3)),
            0x9f => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B3)),

            0xa0 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B4)),
            0xa1 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B4)),
            0xa2 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B4)),
            0xa3 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B4)),
            0xa4 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B4)),
            0xa5 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B4)),
            0xa7 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B4)),

            0xa8 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B5)),
            0xa9 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B5)),
            0xaa => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B5)),
            0xab => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B5)),
            0xac => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B5)),
            0xad => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B5)),
            0xaf => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B5)),

            0xb0 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B6)),
            0xb1 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B6)),
            0xb2 => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B6)),
            0xb3 => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B6)),
            0xb4 => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B6)),
            0xb5 => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B6)),
            0xb7 => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B6)),

            0xb8 => Some(Instruction::RESET(ArithmeticTarget::B, BitPosition::B7)),
            0xb9 => Some(Instruction::RESET(ArithmeticTarget::C, BitPosition::B7)),
            0xba => Some(Instruction::RESET(ArithmeticTarget::D, BitPosition::B7)),
            0xbb => Some(Instruction::RESET(ArithmeticTarget::E, BitPosition::B7)),
            0xbc => Some(Instruction::RESET(ArithmeticTarget::H, BitPosition::B7)),
            0xbd => Some(Instruction::RESET(ArithmeticTarget::L, BitPosition::B7)),
            0xbf => Some(Instruction::RESET(ArithmeticTarget::A, BitPosition::B7)),

            0xc0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B0)),
            0xc1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B0)),
            0xc2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B0)),
            0xc3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B0)),
            0xc4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B0)),
            0xc5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B0)),
            0xc7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B0)),

            0xc8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B1)),
            0xc9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B1)),
            0xca => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B1)),
            0xcb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B1)),
            0xcc => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B1)),
            0xcd => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B1)),
            0xcf => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B1)),

            0xd0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B2)),
            0xd1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B2)),
            0xd2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B2)),
            0xd3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B2)),
            0xd4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B2)),
            0xd5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B2)),
            0xd7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B2)),

            0xd8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B3)),
            0xd9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B3)),
            0xda => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B3)),
            0xdb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B3)),
            0xdc => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B3)),
            0xdd => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B3)),
            0xdf => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B3)),

            0xe0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B4)),
            0xe1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B4)),
            0xe2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B4)),
            0xe3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B4)),
            0xe4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B4)),
            0xe5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B4)),
            0xe7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B4)),

            0xe8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B5)),
            0xe9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B5)),
            0xea => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B5)),
            0xeb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B5)),
            0xec => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B5)),
            0xed => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B5)),
            0xef => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B5)),

            0xf0 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B6)),
            0xf1 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B6)),
            0xf2 => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B6)),
            0xf3 => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B6)),
            0xf4 => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B6)),
            0xf5 => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B6)),
            0xf7 => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B6)),

            0xf8 => Some(Instruction::SET(ArithmeticTarget::B, BitPosition::B7)),
            0xf9 => Some(Instruction::SET(ArithmeticTarget::C, BitPosition::B7)),
            0xfa => Some(Instruction::SET(ArithmeticTarget::D, BitPosition::B7)),
            0xfb => Some(Instruction::SET(ArithmeticTarget::E, BitPosition::B7)),
            0xfc => Some(Instruction::SET(ArithmeticTarget::H, BitPosition::B7)),
            0xfd => Some(Instruction::SET(ArithmeticTarget::L, BitPosition::B7)),
            0xff => Some(Instruction::SET(ArithmeticTarget::A, BitPosition::B7)),

	    _ => None
	}
    }
}
